In [7]:
import numpy as np
from tensorflow import keras
import tensorflow as tf
from sklearn.metrics import confusion_matrix, classification_report

# 讀取 HDF5 模型
model = keras.models.load_model('pose012.hdf5')

# 讀取測試數據
test_data = np.loadtxt('pose10.csv', delimiter=',')
x_test, y_test = test_data[:, 1:], test_data[:, 0].astype(int)

# 進行預測
y_pred = np.argmax(model.predict(x_test), axis=-1)

# 計算混淆矩陣和分類報告
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

# 打印混淆矩陣和分類報告
print("Confusion matrix:")
print(cm)
print("\nClassification report:")
print(report)

129/129 [==============================] - 0s 3ms/step
Confusion matrix:
[[ 926    2   28   12]
 [   5  802   29  225]
 [  52   91  735  105]
 [   0   24   40 1031]]

Classification report:
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       968
           1       0.87      0.76      0.81      1061
           2       0.88      0.75      0.81       983
           3       0.75      0.94      0.84      1095

    accuracy                           0.85      4107
   macro avg       0.86      0.85      0.85      4107
weighted avg       0.86      0.85      0.85      4107



ValueError: Could not open 'pose012.tflite'.

In [9]:
# 推論専用のモデルとして保存
model_save_path = 'pose017.hdf5'
model.save(model_save_path, include_optimizer=False)

In [10]:
# モデルを変換(量子化)
tflite_save_path = 'pose017.tflite'

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quantized_model = converter.convert()

open(tflite_save_path, 'wb').write(tflite_quantized_model)

INFO:tensorflow:Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpdqz8fedi\assets


INFO:tensorflow:Assets written to: C:\Users\ASUS\AppData\Local\Temp\tmpdqz8fedi\assets


7128